import LegalPageShell from "@/components/LegalPageShell";

export default function PrivacyPolicyClient() {
  return (
    <LegalPageShell title="Privacy Policy" updated="2 September 2026">
      <p className="text-[15px] leading-relaxed text-cm-muted">
        This policy explains what personal data Code Myth Technologies (“CMT”, “we”, “us”) collects when you visit
        this website, use the contact/consultation forms, or create a client-portal account — and what we do with
        it.
      </p>

      <section>
        <h2 className="font-display text-xl font-bold tracking-tight text-cm-text">1. Information we collect</h2>
        <ul className="mt-3 list-disc space-y-2 pl-5 text-[15px] leading-relaxed text-cm-muted">
          <li>
            <strong className="text-cm-text">Contact &amp; consultation forms</strong> — name, email address, and
            the project details you choose to share, submitted through the “Start a Project” and business-analyst
            consultation forms.
          </li>
          <li>
            <strong className="text-cm-text">Client-portal accounts</strong> — name, email address, and profile
            information if you sign in (including via Google sign-in), stored using Firebase Authentication.
          </li>
          <li>
            <strong className="text-cm-text">Technical data</strong> — standard server logs (IP address, browser
            type, timestamps) generated by normal web hosting, used only for security (e.g. rate-limiting abusive
            form submissions) and diagnosing errors.
          </li>
        </ul>
        <p className="mt-3 text-[15px] leading-relaxed text-cm-muted">
          We do not run third-party advertising or analytics trackers on this site, and we do not use marketing
          cookies.
        </p>
      </section>

      <section>
        <h2 className="font-display text-xl font-bold tracking-tight text-cm-text">2. How we use your data</h2>
        <p className="mt-2 text-[15px] leading-relaxed text-cm-muted">
          We use the information above to respond to enquiries, schedule consultations, deliver client-portal
          functionality, and protect the site against spam and abuse. We do not use your data to make automated
          decisions that produce legal or similarly significant effects.
        </p>
      </section>

      <section>
        <h2 className="font-display text-xl font-bold tracking-tight text-cm-text">3. Where your data is stored</h2>
        <p className="mt-2 text-[15px] leading-relaxed text-cm-muted">
          Form submissions and account data are stored securely on Firebase (Google Cloud) infrastructure. Contact
          form submissions may also trigger an email notification to our team via our transactional email provider.
          We do not sell your personal data to third parties, and we do not share it with anyone outside CMT except
          the infrastructure providers (Firebase/Google Cloud) needed to operate the site.
        </p>
      </section>

      <section>
        <h2 className="font-display text-xl font-bold tracking-tight text-cm-text">4. Data retention</h2>
        <p className="mt-2 text-[15px] leading-relaxed text-cm-muted">
          We keep enquiry and account data for as long as it’s needed to respond to you, deliver services, and meet
          our legal/accounting obligations, after which it is deleted or anonymised.
        </p>
      </section>

      <section>
        <h2 className="font-display text-xl font-bold tracking-tight text-cm-text">5. Your rights</h2>
        <p className="mt-2 text-[15px] leading-relaxed text-cm-muted">
          You can request access to, correction of, or deletion of your personal data at any time. If you have a
          client-portal account, you can delete your account and associated data directly from the “Delete account”
          option in your profile menu. Otherwise, email{" "}
          <a href="mailto:info@codemyth.in" className="text-cm-accent hover:underline">
            info@codemyth.in
          </a>{" "}
          and we’ll action the request.
        </p>
      </section>

      <section>
        <h2 className="font-display text-xl font-bold tracking-tight text-cm-text">6. Cookies</h2>
        <p className="mt-2 text-[15px] leading-relaxed text-cm-muted">
          We use only the minimum, strictly-necessary cookies/local storage required for authentication sessions
          (via Firebase Authentication) if you sign in — nothing used for advertising or cross-site tracking.
        </p>
      </section>

      <section>
        <h2 className="font-display text-xl font-bold tracking-tight text-cm-text">7. Changes to this policy</h2>
        <p className="mt-2 text-[15px] leading-relaxed text-cm-muted">
          We may update this Privacy Policy from time to time. Material changes will be reflected by updating the
          “Last updated” date above.
        </p>
      </section>

      <section>
        <h2 className="font-display text-xl font-bold tracking-tight text-cm-text">8. Contact</h2>
        <p className="mt-2 text-[15px] leading-relaxed text-cm-muted">
          Questions about this policy or your data can be sent to{" "}
          <a href="mailto:info@codemyth.in" className="text-cm-accent hover:underline">
            info@codemyth.in
          </a>
          . MSME Registration: UDYAM-PY-03-0057608.
        </p>
      </section>
    </LegalPageShell>
  );
}
